//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int CategoryID { get; set; }
        public int EntoryID { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual Entory Entory { get; set; }
    }
}
