//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entory
    {
        public Entory()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int EntoriesID { get; set; }
        public string EntoriesName { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
    }
}
