//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyGole
    {
        public int MonthlyGolesId { get; set; }
        public int UserId { get; set; }
        public int CategoryId { get; set; }
        public int Amount { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
