//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public int Amount { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Memo { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
